version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - SERVERLESS_INFERENCE_URL=${SERVERLESS_INFERENCE_URL}
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
